# Generated by Django 3.0.5 on 2020-05-06 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maze', '0002_apikeys'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='トークン', max_length=260, verbose_name='トークン')),
                ('turn', models.IntegerField(default=0, help_text='ターン', verbose_name='ターン')),
                ('step', models.IntegerField(default=0, help_text='ステップ', verbose_name='ステップ')),
                ('action', models.IntegerField(default=0, help_text='行動', verbose_name='行動')),
            ],
        ),
        migrations.AddField(
            model_name='maze',
            name='level',
            field=models.IntegerField(default=1, help_text='問題のレベル', verbose_name='問題のレベル'),
        ),
        migrations.DeleteModel(
            name='Results',
        ),
        migrations.AddField(
            model_name='practicehistory',
            name='maze',
            field=models.ForeignKey(help_text='迷路', on_delete=django.db.models.deletion.CASCADE, to='maze.Maze', verbose_name='迷路'),
        ),
        migrations.AddField(
            model_name='practicehistory',
            name='user',
            field=models.ForeignKey(help_text='ユーザ名', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ名'),
        ),
    ]
