# Generated by Django 3.0.5 on 2020-05-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0004_auto_20200506_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicehistory',
            name='pos_x',
            field=models.IntegerField(default=0, help_text='現在位置のX座標', verbose_name='現在位置のX座標'),
        ),
        migrations.AddField(
            model_name='practicehistory',
            name='pos_y',
            field=models.IntegerField(default=0, help_text='現在位置のY座標', verbose_name='現在位置のY座標'),
        ),
        migrations.AddField(
            model_name='practicehistory',
            name='vec',
            field=models.IntegerField(default=0, help_text='向き', verbose_name='向き'),
        ),
    ]
