# Generated by Django 3.0.5 on 2020-05-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0005_auto_20200506_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='トークン', max_length=260, verbose_name='トークン')),
                ('status', models.IntegerField(default=0, help_text='ステータス', verbose_name='ステータス')),
            ],
        ),
    ]
